server:
  port: ${PORT:8080}

app:
  twitch:
    demo-mode: ${TWITCH_DEMO_MODE:true}

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: twitch
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: "${TWITCH_CLIENT_ID:demo-client-id}"

  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: "${TWITCH_CLIENT_ID:demo-client-id}"
            client-secret: "${TWITCH_CLIENT_SECRET:demo-client-secret}"
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

logging:
  level:
    twitch: INFO
    twitch.external.TwitchApiClient: ${TWITCH_API_LOG_LEVEL:DEBUG}
